POST http://localhost:3000/user-written-blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NjhhZTI4YTlhYjAyYzRkMGI0YmEwNCIsImlhdCI6MTcxODM2NjcyN30.OYC4MortL3bsdtpwJJWUw9xcppa54C1pZnzur9APp0s
Content-Type: application/json

{
    "page":1,
    "draft":false
}